#pragma once

using namespace ATL;

template <class T>
class CProxy_IAxHellControlEvents : public IConnectionPointImpl<T, &__uuidof(_IAxHellControlEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
